name: fb_auth
description: A Web, Mobile Firebase Auth Plugin
version: 0.0.1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^5.0.4
  firebase_auth: ^0.14.0+5
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
